### ISSUE TITLE
Documentation for annotation API

### ISSUE THREAD

**Issue by finnatsea** [unified-doc/unified-doc#3]
Great work so far. The highlighting functionality as shown on the [ebook demo](https://unified-doc.netlify.app/demos/ebook/) doesn't seem to be documented yet. It looks like that particular demo creates annotations in the following way:

```Javascript 
// Found at https://github.com/unified-doc/docs/blob/main/pages/demos/ebook/ebook.js
  const doc = unifiedDoc({
    annotations: bookmarks,
    annotationCallbacks: {
      onClick: handleRemoveBookmark,
    },
    compiler: [rehype2react, { createElement }],
    content: alice.content,
    filename: alice.filename,
  });
```
Could you shed some light on the purpose of `rehype2react` in this context? I thought that rehype was for markdown conversion. 

A simple example of how to use `annotations` and `annotationCallbacks` would be very helpful.

**Comment by chrisrzhou** [comment]
Hi @downtownbrown19, I'll be updating the docs this weekend.  I formally released packages (`v1.0.0`) last week and this is not up-to-date.  Specifically, the `annotationCallbacks` feature is removed in `unified-doc` but will be moved to `unified-doc-dom` because it is a DOM-based feature.

I would be expecting work to be completed on this weekend and will provide an update in this issue!

`unified-doc` works with `hast` trees (i.e. HTML), which means that all `unified` parsers attached to `unified-doc` parses content to `hast`.  Rehype-based compilers compile `hast` into some output.  The default compiler is a string HTML compiler if you did not provide one.  `rehype2react` is a rehype compiler that compiles `hast` to React elements usable by React.  Hope the explanation makes sense.  The way markdown is supported in `unified-doc` is we have a parser that parses markdown string content to `mdast` (done via `remark-parse`) and tree conversion of `mdast` to `hast` via `remark-rehype`.  In the end, `unified-doc` always ensures the output tree is `hast`, which allows `hast`-based utilities to operate on it.

More details in: https://github.com/unified-doc/unified-doc/blob/main/spec.md#design

**Comment by chrisrzhou** [comment]
And I plan to include common recipes in the `Recipes` docs.  Will take your feedback on including an example for `annotations` and `annotationCallbacks` there!

**Comment by chrisrzhou** [comment]
Might get to this in 1-2 weeks.  Tidying up a few other older repos in the meantime, and applying things I've learned to better managing this repo!
